api:
  host: '0.0.0.0'
  port: 5000
scheduler:
  nodes:
    - name: "node-1"
      status: "Ready"
      total_resources:
        cpu: 16
        memory: 32768
        gpu: 2
        io: 5000
        network: 10000
      used_resources:
        cpu: 4
        memory: 8192
        gpu: 0
        io: 1000
        network: 2000
    - name: "node-2"
      status: "Ready"
      total_resources:
        cpu: 8
        memory: 16384
        gpu: 1
        io: 3000
        network: 8000
      used_resources:
        cpu: 2
        memory: 4096
        gpu: 1
        io: 500
        network: 1000